local myCore = Core

function addScriptFile()
	myCore:loadScript( "media/scripts/main.lua" )
	myCore:loadScript( "media/scripts/input.lua" )
	myCore:loadScript( "media/scripts/assets.lua" )
	myCore:loadScript( "media/scripts/scene.lua" )
	myCore:loadScript( "media/scripts/particles.lua" )
	myCore:loadScript( "media/scripts/mainmenu.lua" )
	myCore:loadScript( "media/scripts/charmenu.lua" )
	myCore:loadScript( "media/scripts/playscene.lua" )
	myCore:loadScript( "media/scripts/level_start.lua" )
	myCore:loadScript( "media/scripts/levels.lua" )
	myCore:loadScript( "media/scripts/characters.lua" )
	myCore:loadScript( "media/scripts/objects.lua" )
	myCore:loadScript( "media/scripts/projectiles.lua" )
	myCore:loadScript( "media/scripts/abilities.lua" )
	myCore:loadScript( "media/scripts/inventory.lua" )
	myCore:loadScript( "media/scripts/items.lua" )
	myCore:loadScript( "media/scripts/loot.lua" )
	myCore:loadScript( "media/scripts/windowMap.lua" )
	myCore:loadScript( "media/scripts/spawningManager.lua" )
	myCore:loadScript( "media/scripts/effects.lua" )
	myCore:loadScript( "media/scripts/upgrades.lua" )
	myCore:loadScript( "media/scripts/tooltips.lua" )
	myCore:loadScript( "media/scripts/abilitybar.lua" )
end

register( "ReloadScript", addScriptFile )