#ifndef CHARACTERFACTION_H_INCLUDED
#define CHARACTERFACTION_H_INCLUDED

enum class CharacterFaction : int {
    FACTION_NEUTRAL,
    FACTION_FRIENDLY,
    FACTION_ENEMY,
};

#endif // CHARACTERFACTION_H_INCLUDED
